PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE iframe (id integer not null,title varchar(200),url varchar(500),idLogin integer not null,primary key(id),foreign key (idLogin) references login(id));
INSERT INTO iframe VALUES(1,'Rock','https://www.youtube.com/embed/Vco19mCx1qw?si=9Lf3ZIf--69XAGIY',1);
INSERT INTO iframe VALUES(2,'titre','https://www.youtube.com/embed/bd_PM1s5STk?si=Z3ttr01ptEAcTDBc',1);
INSERT INTO iframe VALUES(3,'titre2','https://www.youtube.com/embed/459babM2Uuw?si=gMiseR-DbmDvW117',1);
INSERT INTO iframe VALUES(4,'titre3','https://www.youtube.com/embed/pFA1z9IvGTk?si=oAAxclkrEv6BK-zC',1);
INSERT INTO iframe VALUES(5,'titre3Jcb','https://www.youtube.com/embed/pFA1z9IvGTk?si=oAAxclkrEv6BK-zC',2);
CREATE TABLE login (id integer not null,username varchar(50),password varchar(50),primary key(id));
INSERT INTO login VALUES(1,'oscar','123');
INSERT INTO login VALUES(2,'jcb','321');
COMMIT;
